table branches
	lineageTag: a5220ff9-a601-4d4f-9575-b7c7fd2f52e4

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: 35b723ae-8c3e-455f-b859-b1617b7e087f
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column branch_name
		dataType: string
		lineageTag: 1715e17f-e925-4035-941c-9bc2ce205b70
		summarizeBy: none
		sourceColumn: branch_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: b24c944a-7b13-4350-9514-fe90cd315f8e
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: a1484a59-ac1a-4922-af6f-b0362a62648a
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: a781af29-3de7-4c7f-b72a-6e7c2d9432f3
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column manager
		dataType: string
		lineageTag: 9dba727c-dec0-4dea-9df4-9aa105a2a844
		summarizeBy: none
		sourceColumn: manager

		annotation SummarizationSetBy = Automatic

	column opened_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a0e9c0f-c075-4cc5-9815-cab46f1241b3
		summarizeBy: none
		sourceColumn: opened_date

		variation Variation
			isDefault
			relationship: 2ec43bd7-a3e0-44d0-85bf-50b46d2fd655
			defaultHierarchy: LocalDateTable_78f17135-310a-4336-8053-103fc62d08ea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition branches = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\phase1_mock_database\phase1_data\branches.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"branch_id", Int64.Type}, {"branch_name", type text}, {"city", type text}, {"state", type text}, {"phone", type text}, {"manager", type text}, {"opened_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

