table deals
	lineageTag: fb910938-f796-4dc0-84f2-e5592f63f115

	measure 'Total Revenue' = SUM(deals[value])
		lineageTag: 58bf2531-ee8e-40ff-8d06-80fe1dcca92f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Closed Won Deals' = ```
			
			CALCULATE(
			  COUNTROWS(deals),
			  deals[status] = "Closed Won"
			)
			
			```
		formatString: 0
		lineageTag: 0a7be47b-46ad-45e4-ae7c-439dc8849a73

	measure 'Closed Lost Deals' = ```
			
			CALCULATE(
			  COUNTROWS(deals),
			  deals[status] = "Closed Lost"
			)
			
			```
		formatString: 0
		lineageTag: 18c40fb4-11f4-4233-ae3d-b1f808dde569

	measure 'Lead to Close Rate %' =
			
			DIVIDE(  [Closed Won Deals],
			  COUNTROWS(leads), 0
			) * 100
		lineageTag: 6ac9043e-8c8b-46ff-b819-c5960cf1177d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Leads Created' = COUNTROWS(leads)
		formatString: 0
		lineageTag: 43ffb4c3-8f6b-42d9-a46b-812f5113a05c

	measure 'Avg Deal Value' =
			
			AVERAGEX(
			  FILTER(deals,
			    deals[status]="Closed Won"),
			  deals[value]
			)
		lineageTag: 11d5a535-5846-4e80-b6b4-8bc7ba29ca5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Revenue MTD' =
			
			CALCULATE(
			  SUM(deals[value]),
			  deals[status]="Closed Won",
			  DATESMTD(deals[close_date])
			)
		lineageTag: 4a523481-b60d-45ba-9e2d-e3e3923db602

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Revenue YTD' =
			
			CALCULATE(
			  SUM(deals[value]),
			  deals[status]="Closed Won",
			  DATESYTD(deals[close_date])
			)
		lineageTag: 791af385-b0a9-4cd1-837a-0ee6df9d87a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deal_id
		dataType: int64
		formatString: 0
		lineageTag: e6fa82ec-885c-4d75-a8a5-42f6c3c74451
		summarizeBy: none
		sourceColumn: deal_id

		annotation SummarizationSetBy = Automatic

	column lead_id
		dataType: int64
		formatString: 0
		lineageTag: eadf3c31-2f52-4f82-90cd-946c4d5e3d2c
		summarizeBy: sum
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column rep_id
		dataType: int64
		formatString: 0
		lineageTag: 8b8b03c4-e3f7-41ee-b455-dd2bbb5dbb02
		summarizeBy: sum
		sourceColumn: rep_id

		annotation SummarizationSetBy = Automatic

	column close_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9a59a52-081b-4804-84e8-1a34aa65fbe0
		summarizeBy: none
		sourceColumn: close_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column value
		dataType: double
		lineageTag: f892004c-004b-4c5a-9668-393c34c67650
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: ebd07080-9f18-4513-9dee-700e845e1f76
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: 4b3d77a2-28bb-48c1-8ca5-9048d6c1a4d3
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	partition deals = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\phase1_mock_database\phase1_data\deals.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"deal_id", Int64.Type}, {"lead_id", Int64.Type}, {"rep_id", Int64.Type}, {"close_date", type date}, {"value", type number}, {"status", type text}, {"branch_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

